.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2017 Stephen Paul Weber <singpolyma@singpolyma.net>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH POCKET-HOME 1 "August 17, 2017"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pocket-home \- home screen for PocketCHIP
.SH SYNOPSIS
.B pocket-home
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B pocket-home
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBpocket-home\fP provides a lightweight menu, status indicators, and
settings for mobile devices.
.SH OPTIONS
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-fakewifi
Use fake WiFi status.
